default_language_version:
  python: python3
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml

-   repo: local
    hooks:
    -   id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        types: [shell]
        require_serial: true

    -   id: pyupgrade
        name: pyupgrade
        entry: pyupgrade
        language: system
        types: [python]
        require_serial: true

    -   id: black
        name: black
        entry: black
        language: system
        types: [python]
        require_serial: true

    -   id: autoflake
        name: autoflake
        entry: autoflake
        language: system
        types: [python]
        require_serial: true

-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        require_serial: true
        args: [--config, setup.cfg]

    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        require_serial: true

    -   id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        require_serial: true

    -   id: bandit
        name: bandit
        entry: bandit
        language: system
        types: [python]
        require_serial: true
        args: [-c, .bandit.yml, -r, src]
        always_run: true

    -   id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        args: [-m, not integration]
        always_run: true

    -   id: generate-cdk-diagram
        name: generate-cdk-diagram
        entry: make cdk-diagram
        language: system
        pass_filenames: false
        always_run: true
