Resources:
  HelloLambdaServiceRoleE071F162:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: HelloLambdaStack/HelloLambda/ServiceRole/Resource
  HelloLambda3D9C82D6:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: f86e478e5a78e4c7b18e02d8efb007bc1ef16fcba69189eae633486f270d8819.zip
      Role:
        Fn::GetAtt:
          - HelloLambdaServiceRoleE071F162
          - Arn
      Handler: src/handlers/http/hello.handler
      Runtime: python3.9
    DependsOn:
      - HelloLambdaServiceRoleE071F162
    Metadata:
      aws:cdk:path: HelloLambdaStack/HelloLambda/Resource
      aws:asset:path: asset.f86e478e5a78e4c7b18e02d8efb007bc1ef16fcba69189eae633486f270d8819
      aws:asset:is-bundled: false
      aws:asset:property: Code
  ApiGateway11E7F47B:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: ApiGateway
    Metadata:
      aws:cdk:path: HelloLambdaStack/ApiGateway/Resource
  ApiGatewayCloudWatchRoleA41EF9FE:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: HelloLambdaStack/ApiGateway/CloudWatchRole/Resource
  ApiGatewayAccountBC7F34C1:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - ApiGatewayCloudWatchRoleA41EF9FE
          - Arn
    DependsOn:
      - ApiGateway11E7F47B
    Metadata:
      aws:cdk:path: HelloLambdaStack/ApiGateway/Account
  ApiGatewayDeploymentA26796E8b2e1fcf9651b74fbbf19c7b2260d7f23:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: ApiGateway11E7F47B
      Description: Automatically created by the RestApi construct
    DependsOn:
      - ApiGatewayhelloGET00C54D7F
      - ApiGatewayhello4B04412C
    Metadata:
      aws:cdk:path: HelloLambdaStack/ApiGateway/Deployment/Resource
  ApiGatewayDeploymentStageprod1C6D5CD6:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: ApiGateway11E7F47B
      DeploymentId:
        Ref: ApiGatewayDeploymentA26796E8b2e1fcf9651b74fbbf19c7b2260d7f23
      StageName: prod
    DependsOn:
      - ApiGatewayAccountBC7F34C1
    Metadata:
      aws:cdk:path: HelloLambdaStack/ApiGateway/DeploymentStage.prod/Resource
  ApiGatewayhello4B04412C:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - ApiGateway11E7F47B
          - RootResourceId
      PathPart: hello
      RestApiId:
        Ref: ApiGateway11E7F47B
    Metadata:
      aws:cdk:path: HelloLambdaStack/ApiGateway/Default/hello/Resource
  ApiGatewayhelloGETApiPermissionHelloLambdaStackApiGateway0809E910GEThello967C5127:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - HelloLambda3D9C82D6
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: ApiGateway11E7F47B
            - /
            - Ref: ApiGatewayDeploymentStageprod1C6D5CD6
            - /GET/hello
    Metadata:
      aws:cdk:path: HelloLambdaStack/ApiGateway/Default/hello/GET/ApiPermission.HelloLambdaStackApiGateway0809E910.GET..hello
  ApiGatewayhelloGETApiPermissionTestHelloLambdaStackApiGateway0809E910GEThello0A11ACAF:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - HelloLambda3D9C82D6
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: ApiGateway11E7F47B
            - /test-invoke-stage/GET/hello
    Metadata:
      aws:cdk:path: HelloLambdaStack/ApiGateway/Default/hello/GET/ApiPermission.Test.HelloLambdaStackApiGateway0809E910.GET..hello
  ApiGatewayhelloGET00C54D7F:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId:
        Ref: ApiGatewayhello4B04412C
      RestApiId:
        Ref: ApiGateway11E7F47B
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        IntegrationResponses:
          - StatusCode: "200"
        Type: AWS
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - HelloLambda3D9C82D6
                  - Arn
              - /invocations
      MethodResponses:
        - StatusCode: "200"
    Metadata:
      aws:cdk:path: HelloLambdaStack/ApiGateway/Default/hello/GET/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/1WPQW/CMAyFfwv31Exw6Lkw7TaB2A9AJvU6r21SNY5QVfW/z0mZxk7ve7ae87KDXQkvG7yHwtZt0fEN5g9B2xodXecO+1uNML9FZ4W9M8dP98xnGnsOQd1iGHuYL76jtEi6mLC/YggkAaok6uEQbUtywEAGB25Q6I6T5ihINXCO/mFlrY9OzCsNnZ96UtTpk9OqTX5vBY36OFrK53/N4+bK7yRfvk6jlZbF5Gopz65Ji1OUIcq/lPLRu5olf/Q8adJt91BCufkOzMWoJbknuKz6A8yRXB1VAQAA
    Metadata:
      aws:cdk:path: HelloLambdaStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Outputs:
  ApiGatewayEndpoint5AA8EC3A:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: ApiGateway11E7F47B
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: ApiGatewayDeploymentStageprod1C6D5CD6
          - /
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

