name: Build/test/deploy

on:
  workflow_dispatch:
  push:

jobs:
  build-test-deploy:
    name: Build/test/deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/

      - run: npm install -g aws-cdk

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9.x

      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements-dev.txt') }}-${{ hashFiles('requirements.txt') }}

      - run: pip install -r ./requirements-dev.txt

      - run: pip-audit

      - run: pre-commit run --all-files

      - run: cdk synth
        if: ${{ github.event.ref == 'refs/heads/main' }}

      - uses: aws-actions/configure-aws-credentials@v1
        if: ${{ github.event.ref == 'refs/heads/main' }}
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - run: cdk deploy
        if: ${{ github.event.ref == 'refs/heads/main' }}
