name: Build/test/deploy

on:
  workflow_dispatch:
  cron: '0 10 * * *' # 10am every day
jobs:
  audit-dependencies:
    name: Build/test/deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.x'

      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements-dev.txt') }}-${{ hashFiles('requirements.txt') }}

      - run: pip install --upgrade pip

      - run: pip install -r ./requirements-dev.txt

      - run: pip-audit
